### PR TITLE
fixes #26: UnknownDirective value must be representable as a string

### LINKED ISSUE #26: validate that UnknownDirective nodes do not contain line terminator characters

### PR DESCRIPTION
**Pull request by michaelficarra**
Don't merge. I can't think of a better way than indirect eval other than relying on a whole damn lexer. Also, it's not foolproof (and a security vulnerability): `{ type: "UnknownDirective", value: "\"; <arbitrary code execution> \""}`.

Fixes #26.

### CODE REVIEW

**Comment by ikarienator** [comment]
RegExp it and `JSON.stringify`?

**Comment by michaelficarra** [comment]
I don't know how that would work for single quoted strings. Please add a commit on this branch or make a PR to it.

**Comment by ikarienator** [comment]
Try:

```js
'string'.replace(/\\'/g, '\'').replace(/"/g, '\\\'')
```

**Comment by bakkot** [comment]
outdated

**Pull request closed without merging**
